config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'

  get '/users/login', to: 'session#new_user'
  post '/users/sessions', to: 'session#create_user'
  delete '/users/logout', to: 'session#destroy_user'

  get '/breeders/login', to: 'session#breeder_new'
  post '/breeders/sessions', to: 'session#breeder_create'
  delete '/breeders/logout', to: 'session#breeder_destroy'

  patch '/breeders', to: 'breeders#sort_by_rating', as: 'sort_breeders'
  post '/breeders/:id', to: 'breeders#rate', as: "rate_breeders"

  get '/pets/:id/adopted_new', to: 'pets#adopted_new', as: 'adopted_new'
  post '/pets/:id/adopted', to: 'pets#adopted', as: 'adopted'

  get '/exit', to: 'session#destroy_both'
  delete '/exit', to: 'session#destroy_both'

  get '/profile', to: 'session#get_profile'

  get '/about', to: 'home#about'

resources :users
resources :pets
resources :breeders


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_one :adopt
    has_one :user, through: :adopt
    belongs_to :breeder


    def self.breed_search(search)
        if search && search.length>1
        Pet.all.select do |pet|
          pet.breed == search
        end
        else Pet.all
        end
    end

    def self.age_search(search)
        if search && search.length>=1 && search.to_i >=1
        Pet.all.select do |pet|
          pet.age == search.to_i
        end
        else Pet.all
        end
    end

    def self.size_search(search)
        if search && search.length>1
        Pet.all.select do |pet|
          pet.size == search
        end
        else Pet.all
        end
    end

    def self.gender_search(search)
        if search && search.length>1
        Pet.all.select do |pet|
          pet.gender == search
        end
        else Pet.all
        end
    end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # before_action :user_authorized

  def index
    
    if params[:breed_search]
      @pets= Pet.breed_search(params[:breed_search])
      elsif params[:size_search]
    @pets= Pet.size_search(params[:size_search])
      elsif params[:gender_search]
    @pets= Pet.gender_search(params[:gender_search])
      elsif params[:age_search]
    @pets= Pet.age_search(params[:age_search])
      else @pets = Pet.all
    end
    @adopt = Adopt.all.map{|adopt| adopt.pet_id}
      @unadopted_pets = @pets.select do |pet|
      !@adopt.include?(pet.id)
    end
  end

  def show
    @user = current_user
    @pet = Pet.find(params[:id])
    @adopt = Adopt.all.find do |adopt|
      adopt.pet_id == @pet.id
     end
   
    @suggested_pets = Pet.all.select do |pet| 
    pet.breed == @pet.breed && pet!=@pet
    end
  end


  def adopted_new
    @pet = Pet.find(params[:id])
  end

  def adopted
    @pet = Pet.find(params[:id])
    @user = current_user
    @adopt = Adopt.create(user:@user, pet:@pet)
    redirect_to adopted_new_path
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @breeder = Breeder.find(session[:breeder_id])
      if @pet.save
        redirect_to @breeder
      else 
        flash[:messages] = @pet.errors.full_messages[0]
        render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update (pet_params)
    redirec_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :age, :breed, :size, :gender, :image, :breeder_id, :breed_search, :age_search, :size_search, :gender_search)
  end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/adopted.html.erb
<h2><%=@pet.name%> has beed adopted!</h2>

app/views/pets/adopted_new.html.erb
<div id = "pets_show">
<br>
<h2 id ="h2">Congratulations! You've just adopted <%=@pet.name%>!</h2>
<br><%= image_tag @pet.image, :width => 350, :height => 200 %><br>
<br>
 <p>Plese allow to 2-3-business days to complete the paperwork and ship <%=@pet.name%> to you.</p>
 <h6><%= button_to "See other dogs", pets_path, method: :get%></h6>
 </div>

app/views/pets/edit.html.erb
<h1>Pets#edit</h1>
<p>Find me in app/views/pets/edit.html.erb</p>

app/views/pets/index.html.erb
<div id="pets_show">
<br>
<div align="center">
<h1>Choose your future Dog:</h1>
</div>
<br>
<div id="pet_index_background">
<div class="row row-cols-4">

<div class="col">
<p>Seach by breed:</p>
<%=form_tag pets_path, method: :get do%>
<%=text_field_tag :breed_search, params[:breed_search]%>
<%=submit_tag ("Search")%>
<%end%>
</div>

<div class="col">
<p>Seach by age:</p>
<%=form_tag pets_path, method: :get do%>
<%=number_field_tag :age_search, params[:age_search]%>
<%=submit_tag ("Search")%>
<%end%>
</div>

<div class="col">
<p>Seach by gender (male, female):</p>
<%=form_tag pets_path, method: :get do%>
<%=text_field_tag :gender_search, params[:gender_search]%>
<%=submit_tag ("Search")%>
<%end%>
</div>


<div class="col">
<p>Seach by size (small, medium, big) :</p>
<%=form_tag pets_path, method: :get do%>
<%=text_field_tag :size_search, params[:size_search]%>
<%=submit_tag ("Search")%>
<%end%>
</div>
</div>

<br>


  <div class="row row-cols-4">
    <% @unadopted_pets.each do |pet| %>
    <div class="col">
        <%= image_tag pet.image, :width => 350, :height => 200%><br>
            <%=link_to pet.name, pet_path(pet)%> |
            <%= pet.breed %> |
            <%= pet.age %> |
            <%= pet.gender %>
    </div>
    <%end%>
 </div>


</div>




 

app/views/pets/new.html.erb
<head>
<style> 
input {
  width: 15%;
  padding: 5px 10px;
  margin: 10px 0;
  margin-left: 40px;
  box-sizing: border-box;
  border: 3px solid #ccc;
  -webkit-transition: 0.5s;
  transition: 0.5s;
  outline: none;
}

input[type=text]:focus {
  border: 3px solid #555;
}
</style>
</head>

<br>
<div align="center">
<h1> Add Dog to Your Kennel </h1>
</div>

<% if flash[:messages] %>
<% flash[:messages] %>
<%end%>




<%= form_for @pet do |f| %>
       Name <br> <%= f.text_field :name%>
  <br> Age <br> <%= f.number_field :age %>
  <br> Breed <br> <%= f.text_field :breed %>
  <br> Size <br> <%= f.text_field :size %>
  <br> Gender <br> <%= f.text_field :gender %>
  <br> Image <br> <%= f.text_field :image %>
  <br> Breeder <br> <%= f.collection_select :breeder_id, Breeder.all, :id, :name %>
  <br> <%= f.submit "Create a Pet" %>
<% end %>
</div>

app/views/pets/show.html.erb
<div id="pets_show">

<br>
<%if @adopt%>
<div align="center" >
<h1>Hi there! I'm <%=@pet.name%></h1>
<br><%= image_tag @pet.image, :width => 350, :height => 200 %><br>
<p>I'd like to introduce myself: I'm <%=@pet.age%> years old, a <%=@pet.size%> size <%=@pet.breed%>, I'm a <%=@pet.gender%>. Nice to meet you!</p>
</div>

<%else%>

<div align="center">
<h1>Hi there! I'm <%=@pet.name%> and I'd love to be adopted!</h1>
<br><%= image_tag @pet.image, :width => 350, :height => 200 %><br>
<p>I'd like to introduce myself: I'm <%=@pet.age%> years old, a <%=@pet.size%> <%=@pet.breed%>, I'm a <%=@pet.gender%>. Nice to meet you!</p>
<% if @user %>  
<button type="button" class="btn btn-warning">
<%= link_to "Adopt me!", adopted_path, method: :post%>
</button>
<button type="button" class="btn btn-warning">
<%= link_to "See the breeder", breeder_path(@pet.breeder), method: :get%>
</button>
<% else %>
In order to adopt please <%= link_to "Sign In",users_login_path %>
<%end%>
</div>

<%end%>
<br>
<br>
<h4>Suggested Similar Dogs:</h4>

  <div class="row row-cols-4">
    <%@suggested_pets.map do |dog|%>
        <div class="col">
    <%=image_tag dog.image, :width => 350, :height => 200%>
    <%=link_to dog.name, pet_path(dog)%> |
            <%= dog.breed %> |
            <%= dog.age %> years old |
            <%= dog.gender %>
    </div>
    <%end%>
</div>

</div>