config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'

  get '/users/login', to: 'session#new_user'
  post '/users/sessions', to: 'session#create_user'
  delete '/users/logout', to: 'session#destroy_user'

  get '/breeders/login', to: 'session#breeder_new'
  post '/breeders/sessions', to: 'session#breeder_create'
  delete '/breeders/logout', to: 'session#breeder_destroy'

  patch '/breeders', to: 'breeders#sort_by_rating', as: 'sort_breeders'
  post '/breeders/:id', to: 'breeders#rate', as: "rate_breeders"

  get '/pets/:id/adopted_new', to: 'pets#adopted_new', as: 'adopted_new'
  post '/pets/:id/adopted', to: 'pets#adopted', as: 'adopted'

  get '/exit', to: 'session#destroy_both'
  delete '/exit', to: 'session#destroy_both'

  get '/profile', to: 'session#get_profile'

  get '/about', to: 'home#about'

resources :users
resources :pets
resources :breeders


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def breeder_new
  end

  def breeder_create
    @breeder = Breeder.find_by_name(params[:name])
      if @breeder && @breeder.authenticate(params[:password])
        session[:breeder_id] = @breeder.id
        redirect_to breeder_path(@breeder)
      else
      
        flash.now[:messages] = "Sorry! Breeder name or password is not correct. Tty again."
        render :breeder_new
      end
    end

    def breeder_destroy
      session[:breeder_id] = nil
      redirect_to ""
    end

    def new_user
    end

    def create_user
      @user = User.find_by_name(params[:name])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else 
        flash.now[:messages] = "Sorry! User name or password is not correct. Try again."
        render :new_user
      end
    end

    def destroy_user
      session[:user_id] = nil
      redirect_to ""
    end

    def destroy_both
      if
      session[:user_id]
      session[:user_id] = nil
      else
      session[:breeder_id]
      session[:breeder_id] = nil
      end
      redirect_to ""
    end


    def get_profile
      if
        session[:user_id]
        redirect_to user_path(current_user)
        elsif
        session[:breeder_id]
        redirect_to breeder_path(current_breeder)
        else
          redirect_to ""
        end
    end
      

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/breeder_new.html.erb
<div align="center">
<br><br>
<h1>Breeder Log In</h1>
<br>

<%= form_tag '/breeders/sessions' do %>
   Name: <%= text_field_tag "name"%>
    Password: <%= password_field_tag "password"%>
    <%= submit_tag "Submit"%>
<%end%>
<br>
<%= button_to "New Breeder", new_breeder_path, method: :get %>

<br>
<% if flash[:messages] %>
<%= flash.now[:messages] %>
<%end%>

</div>

app/views/session/new.html.erb
Breeder Log In

<%= form_tag '/breeders/sessions' do %>
    <%= text_field_tag "name"%>
    <%= text_field_tag "password"%>
    <%= submit_tag "Submit"%>
<%end%>


<%= form_tag '/users/sessions' do %>
    <%= text_field_tag "name"%>
    <%= text_field_tag "password"%>
    <%= submit_tag "Submit"%>
<%end%>

app/views/session/new_user.html.erb
<div align="center">

<br><br>
<h1>User Log In</h1>
<br>
<%= form_tag '/users/sessions' do %>
   Name: <%= text_field_tag "name"%>
    Password: <%= password_field_tag "password"%>
    <%= submit_tag "Submit"%>
<%end%>
<br>
<%= button_to "New User", new_user_path, method: :get %>
<br>
<% if flash[:messages] %>
<%= flash.now[:messages] %>
<%end%>
</div>