config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'

  get '/users/login', to: 'session#new_user'
  post '/users/sessions', to: 'session#create_user'
  delete '/users/logout', to: 'session#destroy_user'

  get '/breeders/login', to: 'session#breeder_new'
  post '/breeders/sessions', to: 'session#breeder_create'
  delete '/breeders/logout', to: 'session#breeder_destroy'

  patch '/breeders', to: 'breeders#sort_by_rating', as: 'sort_breeders'
  post '/breeders/:id', to: 'breeders#rate', as: "rate_breeders"

  get '/pets/:id/adopted_new', to: 'pets#adopted_new', as: 'adopted_new'
  post '/pets/:id/adopted', to: 'pets#adopted', as: 'adopted'

  get '/exit', to: 'session#destroy_both'
  delete '/exit', to: 'session#destroy_both'

  get '/profile', to: 'session#get_profile'

  get '/about', to: 'home#about'

resources :users
resources :pets
resources :breeders


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :adopts
    has_many :pets, through: :adopts

    validates_numericality_of :age, :greater_than_or_equal_to => 16
    validates :name, uniqueness: true
    validates :password, length: { minimum: 5 }, allow_blank: false
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
    @adopt = Adopt.all.find do |adopt|
      adopt.user_id == @user.id
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else 
      flash.now[:messages] = @user.errors.full_messages[0]
      render :new
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :age, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br><br><br>
<div align="center"><h1>Edit Your Profile</h1>

<%= form_for @user do |f| %>
Name: <%= f.text_field :name %>
Age: <%= f.number_field :age %>
<%=f.submit%>
<%end%>
</div>

app/views/users/index.html.erb
<br>
<br>
<h1> Active Users</h1>


<ul>
<% @users.each do |user|%>
<li><%= link_to  user.name, user_path(user) %></li>
<%end%>
</ul>

app/views/users/new.html.erb
<br><br>
<div align="center"><h1>Create a Profile</h1>
<br>
<%= form_for @user do |f| %>
Name: <%= f.text_field :name %>
Age: <%= f.number_field :age %>
Password: <%= f.password_field :password %>
<%=f.submit "Create Account"%>
<%end%>
<br>
<br>

<% if flash[:messages] %>
<%= flash.now[:messages] %>
<%end%>


</div>

app/views/users/show.html.erb
<br><br>
<div align="center"><h1><%=@user.name%>'s Profile</h1></div>

<%if @adopt%>
<h2> Dogs Adopted:</h2>

  <div class="row row-cols-3">
<%@user.pets.each do |dog|%>
        <div class="col">
    <ul style="list-style: none;">
    <li>
        <%= image_tag dog.image, :width => 350, :height => 200 %>
    </li>
        <%= link_to dog.name, pet_path(dog) %><br>
        Age: <%= dog.age %><br>
        Breed: <%= dog.breed %><br>
        Gender: <%= dog.gender %><br>
        Size: <%= dog.size %><br>
        Adopted from <%= link_to dog.breeder.name, breeder_path(dog.breeder) %>
        </ul>
        </div>
<%end%>
</div>

<%else%>
You have yet to adopt a pet! Go search available <%=link_to "pets", pets_path%>
<%end%>