config/routes.rb
Rails.application.routes.draw do
  
  root 'home#home'

  get '/users/login', to: 'session#new_user'
  post '/users/sessions', to: 'session#create_user'
  delete '/users/logout', to: 'session#destroy_user'

  get '/breeders/login', to: 'session#breeder_new'
  post '/breeders/sessions', to: 'session#breeder_create'
  delete '/breeders/logout', to: 'session#breeder_destroy'

  patch '/breeders', to: 'breeders#sort_by_rating', as: 'sort_breeders'
  post '/breeders/:id', to: 'breeders#rate', as: "rate_breeders"

  get '/pets/:id/adopted_new', to: 'pets#adopted_new', as: 'adopted_new'
  post '/pets/:id/adopted', to: 'pets#adopted', as: 'adopted'

  get '/exit', to: 'session#destroy_both'
  delete '/exit', to: 'session#destroy_both'

  get '/profile', to: 'session#get_profile'

  get '/about', to: 'home#about'

resources :users
resources :pets
resources :breeders


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/breeder.rb
class Breeder < ApplicationRecord
    has_secure_password

    has_many :pets

    validates :name, uniqueness: true
    validates :rating, numericality: true, :allow_nil => true
    validates :password, length: { minimum: 5 }, allow_blank: false, on: :create
end

app/controllers/breeders_controller.rb
class BreedersController < ApplicationController

  def index
      @breeders = Breeder.all
  end

  def show
    @breeder = Breeder.find(params[:id])
    @profile = session[:breeder_id]
    @user = current_user
  end

  def new
    @breeder = Breeder.new
  end

  def create
    @breeder = Breeder.new(breeder_params)
    if @breeder.save
      session[:breeder_id] = @breeder.id
      redirect_to breeder_path(@breeder)
    else 
      flash.now[:messages] = @breeder.errors.full_messages[0]
      render :new
    end
  end

  def edit
    @breeder = Breeder.find(params[:id])
  end

  def update
    @breeder = Breeder.find(params[:id])
    if params[:breeder][:rating]
      @breeder.update!(rating: params[:breeder][:rating])
    else
      @breeder.update!(breeder_params)
    end
    redirect_to breeder_path(@breeder)
  end

  def sort_by_rating
    @breeders = Breeder.all.sort_by{|b| b.rating}.reverse
    render :index
  end

  def dog_sort
    @breeders = Breeder.all.sort_by{|b| b.pets.count}.reverse
    render :index
  end

  def destroy
    @breeder = Breeder.find(params[:id])
    @breeder.destroy
    redirect_to breeders_path
  end

  private

  def breeder_params
    params.require(:breeder).permit(:name, :password, :rating)
  end
end

app/helpers/breeders_helper.rb
module BreedersHelper
end

app/views/breeders/edit.html.erb
<br><br><br>
<div align="center"><h1>Edit a Breeder</h1>

<%= form_for @breeder do |f| %>
Name: <%= f.text_field :name %>
Password: <%= f.password_field :password %>
<%=f.submit%>
<%end%>
</div>

app/views/breeders/index.html.erb
<div align="center">
<br>
<h1> Active Breeders </h1>

<br>
<button type="button" class="btn btn-warning">
<%= link_to "Sort By Highest Rating", sort_breeders_path, method: :patch %> 
</button>
<br>
</div>

<div class="container">
<div align="right">
<% @breeders.each do |breeder|%>
<div class="page">
<%= link_to  breeder.name, breeder_path(breeder) %><br>
<%breeder.rating.to_i.times do %>
                <img src="https://upload.wikimedia.org/wikipedia/commons/2/29/Gold_Star.svg" width="15" height="15">
                <% end %><br>

        <%= breeder.pets.count %> dogs available <br>
        <br>
        </div>
<%end%>
</ul>
</div>
</div>

app/views/breeders/new.html.erb
<br><br>
<div align="center"><h1>Register a Breeder</h1>
<br>
<%= form_for @breeder do |f| %>
Name: <%= f.text_field :name %>
Password: <%= f.password_field :password %>
<%=f.submit%>
<%end%>

<br>
<br>

<% if flash[:messages] %>
<%= flash.now[:messages] %>
<%end%>

</div>

app/views/breeders/show.html.erb
<br>
<div align="center" id="pet_index_background">
<h1><%=@breeder.name%>'s Profile</h1>
<%@breeder.rating.to_i.times do %>
<img src="https://upload.wikimedia.org/wikipedia/commons/2/29/Gold_Star.svg" width="15" height="15">
<% end %><br>

<br>
<% if @user %>
 <%= form_for @breeder do |f| %>
    <%= f.number_field :rating %>
 <%= f.submit "Rate #{@breeder.name}" %>
 <%end%>
<%end%>

 <% if @breeder.id == @profile %>
 <div align="center">
 <button type="button" class="btn btn-warning">
    <%= link_to "Add Dogs", new_pet_path, method: :get %> 
    </button>
    <button type="button" class="btn btn-warning">
    <%= link_to "Edit Breeder", edit_breeder_path, method: :get%> 
    </button>
    <button type="button" class="btn btn-warning">
    <%= link_to "Delete Breeder", breeder_path(@breeder), method: :delete %> 
    </button>
<%end%>
<br>
<h4>Dogs Available:</h4>
  <div class="row row-cols-4">
<% @breeder.pets.each do |dog|%>
    <div class="col">
        <%= image_tag dog.image, :width => 350, :height => 200 %>
            <%= link_to dog.name, pet_path(dog) %></li>
            Age: <%= dog.age %><br>
            Breed: <%= dog.breed %><br>
            Gender: <%= dog.gender %><br>
            Size: <%= dog.size %><br>
        <% if @breeder.id == @profile %>
            <%= button_to "Unlist Dog", pet_path(dog), method: :delete %>
        <%end%>
        </div>
<%end%>
</div>
</div>